blueprint:
  name: Auto Rolladen
  description: Rolladensteuerung
  domain: automation
  source_url: https://raw.githubusercontent.com/MovingLlama/HomeAssistant/master/Blueprints/raffstore.yaml
  input:
    switch:
      name: Switch 1
      description: Entity that is changing Values, testet with Ikea tradfri via zigbee2mqtt
      selector:
        entity:
          domain:
          - sensor
          multiple: false