blueprint:
  name: Auto Raffstore
  description: Raffstoresteuerung
  domain: automation
  source_url: https://raw.githubusercontent.com/MovingLlama/HomeAssistant/master/Blueprints/AutoRaffstore.yaml
  input:
    aktiv:
      name: Aktiv
      selector:
        entity:
          domain:
          - input_boolean
          multiple: false
    raffstore:
      name: Raffstore
      selector:
        entity:
          domain:
          - cover
          multiple: false
    schalter_1:
      name: Schalter 1
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    schalter_1_auf:
      name: Schalter 1 Auf Befehl
      default: open
    schalter_1_zu:
      name: Schalter 1 Zu Befehl
      default: close
    schalter_2:
      name: Schalter 2
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    schalter_2_auf:
      name: Schalter 2 Auf Befehl
      default: open
    schalter_2_zu:
      name: Schalter 2 Zu Befehl
      default: close
    sonnenaufgang_offset:
      name: Sonnenaufgang Verzögerung
      default: 03:00:00
      selector:
        text: {}
    sunnenungergang_offset:
      name: Sonnenuntergang Verzögerung
      default: '- 00:30:00'
      selector:
        text: {}
    aussentemperatur_sensor:
      name: Außentemperatur Sensor
      default: sensor.gw1100a_v2_1_8_outdoor_temperature
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - temperature
          multiple: false
    aussentemperatur_schliessen:
      name: Außentemperatur Schließen
      default: 24
      selector:
        number:
          max: 40.0
          min: 10.0
          step: 1.0
          unit_of_measurement: °C
          mode: slider
    aussentemperatur_offnen:
      name: Außentemperatur Öffnen
      default: 22
      selector:
        number:
          max: 40.0
          min: 10.0
          step: 1.0
          unit_of_measurement: °C
          mode: slider
    raffstore_abend:
      name: Raffstore Abend/Heiß
      default: 25
      selector:
        number:
          max: 100.0
          min: 0.0
          step: 5.0
          unit_of_measurement: '%'
          mode: slider
    raffstore_nacht:
      name: Raffstore Nacht
      default: 0
      selector:
        number:
          max: 100.0
          min: 0.0
          step: 5.0
          unit_of_measurement: '%'
          mode: slider
    fenstersensor:
      name: Fenstersensor
      default: input_boolean.helperfakesensor
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false
    sonnenposition_start:
      name: Sonnenposition Schließen
      default: 60
      selector:
        number:
          max: 365.0
          min: 0.0
          step: 1.0
          unit_of_measurement: '°'
          mode: slider
    sonnenposition_ende:
      name: Sonnenposition Öffnen
      default: 120
      selector:
        number:
          max: 365.0
          min: 0.0
          step: 1.0
          unit_of_measurement: '°'
          mode: slider


mode: restart
max_exceeded: silent

trigger:
- platform: state
  entity_id:
  - !input schalter_1
  to: !input schalter_1_auf
  id: auf
- platform: state
  entity_id:
  - !input schalter_1
  to: !input schalter_1_zu
  id: zu
- platform: state
  entity_id:
  - !input schalter_2
  to: !input schalter_2_auf
  id: auf
- platform: state
  entity_id:
  - !input schalter_2
  to: !input schalter_2_zu
  id: zu
- platform: sun
  event: sunset
  offset: !input sunnenungergang_offset
- platform: sun
  event: sunrise
  offset: !input sonnenaufgang_offset
- platform: sun
  event: sunset
- platform: sun
  event: sunrise
- platform: numeric_state
  entity_id:
  - !input aussentemperatur_sensor
  above: !input aussentemperatur_schliessen
- platform: numeric_state
  entity_id:
  - !input aussentemperatur_sensor
  below: !input aussentemperatur_offnen
- platform: state
  entity_id:
  - !input fenstersensor
- platform: state
  entity_id:
    - sun.sun
  attribute: azimuth
  to: !input sonnenposition_start
- platform: state
  entity_id:
    - sun.sun
  attribute: azimuth
  to: !input sonnenposition_ende

action:
- choose:
  - conditions:
    - condition: trigger
      id: auf
    sequence:
    - choose:
      - conditions:
          - condition: or
            conditions:
            - condition: state
              entity_id: 
                - !input raffstore
              state: opening
            - condition: state
              entity_id: 
                - !input raffstore
              state: closing
        sequence:
          - service: cover.stop_cover
            data: {}
            target:
              entity_id:
                - !input raffstore
      default:
        - service: cover.open_cover
          data: {}
          target:
              entity_id:
                - !input raffstore
  - conditions:
    - condition: trigger
      id: zu
    sequence:
    - choose:
      - conditions:
          - condition: or
            conditions:
            - condition: state
              entity_id:
                - !input raffstore
              state: opening
            - condition: state
              entity_id:
                - !input raffstore
              state: closing
        sequence:
          - service: cover.stop_cover
            data: {}
            target:
              entity_id:
                - !input raffstore
      default:
        - service: cover.close_cover
          data: {}
          target:
              entity_id:
                - !input raffstore
  default:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id:
            - !input fenstersensor
          state: "on"
        - condition: or
          conditions:
          - condition: state
            entity_id:
              - !input raffstore
            state: "closed"
          - condition: state
            entity_id:
              - !input raffstore
            state: "closing"
      sequence:
        - service: cover.set_cover_position
          data:
            position: !input raffstore_abend
          target:
            entity_id:
              - !input raffstore
    default:
    - choose:
      - conditions:
        - condition: and
          conditions:
          - condition: sun
            before: sunset
            after: sunrise
            before_offset: !input sunnenungergang_offset
            after_offset: !input sonnenaufgang_offset
          - condition: state
            entity_id:
            - !input aktiv
            state: "on"
          - condition: numeric_state
            entity_id: sun.sun
            attribute: azimuth
            above: !input sonnenposition_start
            below: !input sonnenposition_ende
        sequence:
          - service: cover.set_cover_position
            data:
              potion: !input raffstore_abend
            target:
                entity_id:
                  - !input raffstore
      - conditions:
        - condition: and
          conditions:
          - condition: sun
            before: sunset
            after: sunrise
            before_offset: !input sunnenungergang_offset
            after_offset: !input sonnenaufgang_offset
          - condition: state
            entity_id:
            - !input aktiv
            state: "on"
          - condition: or
            conditions:
            - condition: numeric_state
              entity_id: sun.sun
              attribute: azimuth
              below: !input sonnenposition_start
            - condition: numeric_state
              entity_id: sun.sun
              attribute: azimuth
              above: !input sonnenposition_ende
        sequence:
          - service: cover.open_cover
            data: {}
            target:
                entity_id:
                  - !input raffstore
      - conditions:
        - condition: and
          conditions:
          - condition: or
            conditions:
            - condition: sun
              before: sunrise
              before_offset: !input sonnenaufgang_offset
            - condition: sun
              after: sunset
              after_offset: !input sunnenungergang_offset
          - condition: state
            entity_id:
            - !input aktiv
            state: "on"
        sequence:
          - service: cover.set_cover_position
            data:
              potion: !input raffstore_abend
            target:
                entity_id:
                  - !input raffstore
      - conditions:
        - condition: and
          conditions:
          - condition: or
            conditions:
            - condition: sun
              before: sunrise
            - condition: sun
              after: sunset
          - condition: state
            entity_id:
            - !input aktiv
            state: "on"
        sequence:
          - service: cover.set_cover_position
            data:
              potion: !input raffstore_nacht
            target:
                entity_id:
                  - !input raffstore