blueprint:
  name: Raffstoresteuerung
  description: Controlling Covers based on Sun state, Wind, Rain and manual imput.
  domain: automation
  source_url: https://raw.githubusercontent.com/MovingLlama/HomeAssistant/master/Blueprints/raffstore.yaml
  input:
    switch:
      name: Switch 1
      description: Entity that is changing Values, testet with Ikea tradfri via zigbee2mqtt
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    up:
      name: Up Value Switch 1
      description: Value for opening covers
      default: up
    down:
      name: Down Value Switch 1
      description: Value for closing covers
      default: down
    switch_2:
      name: Switch 2
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    up_2:
      name: Up Value Switch 2
      description: Value for opening covers
      default: up
    down_2:
      name: Down Value Switch 2
      description: Value for closing covers
      default: down
    raff:
      name: Raffstore Entity
      selector:
        entity:
          domain:
          - cover
          multiple: false
    sunrise_offset:
      name: Offset Sunrise
      description: Offset for Sunrise time
      default: 00:20:00
      selector:
        text: {}
    sunset_offset:
      name: Offset Sunset
      description: Offset for Sunset time
      default: '- 00:20:00'
      selector:
        text: {}
    outside_temperature:
      name: Outside Temerature
      description: Outside Temperature for heating automation
      default:
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - temperature
          multiple: false
    outside_control_temp:
      name: Offset Temperature Close
      description: Temperature at witch the blindes are opening
      default: 15
      selector:
        number:
          max: 40.0
          min: 10.0
          step: 1.0
          unit_of_measurement: °C
          mode: slider
    outside_control_temp_low:
      name: Offset Temperature Close
      description: Temperature at witch the blindes are opening
      default: 15
      selector:
        number:
          max: 40.0
          min: 10.0
          step: 1.0
          unit_of_measurement: °C
          mode: slider
    outside_control_close:
      name: Offset Close Temperature Closed
      description: How far will it be closeing the blindes when hot
      default: 75
      selector:
        number:
          max: 100.0
          min: 0.0
          step: 1.0
          unit_of_measurement: '%'
          mode: slider
    close_if_dark:
      name: Offset Close after dark
      description: How far will it be closeing the blindes when evening
      default: 30
      selector:
        number:
          max: 100.0
          min: 0.0
          step: 1.0
          unit_of_measurement: '%'
          mode: slider
    window_sensor:
      name: Fenstersensor
      default: input_boolean.helperfakesensor
      selector:
        entity:
          domain:
          - binary_sensor
          multiple: false

mode: restart
max_exceeded: silent
trigger:
- platform: state
  entity_id:
  - !input switch
  to: !input up
  id: up
- platform: state
  entity_id:
  - !input switch
  to: !input down
  id: down
- platform: state
  entity_id:
  - !input switch_2
  to: !input up_2
  id: up
- platform: state
  entity_id:
  - !input window_sensor
  to: 'on'
  id: up
- platform: state
  entity_id:
  - !input window_sensor
- platform: state
  entity_id:
  - !input switch_2
  to: !input down_2
  id: down
- platform: sun
  event: sunset
  offset: !input sunset_offset
- platform: sun
  event: sunset
- platform: sun
  event: sunrise
  offset: !input sunrise_offset
- platform: sun
  event: sunrise
- platform: numeric_state
  entity_id:
  - !input outside_temperature
  above: !input outside_control_temp
- platform: numeric_state
  entity_id:
  - !input outside_temperature
  below: !input outside_control_temp_low
- platform: state
  entity_id:
  - !input raff
  to: 'closing'

action:
- choose:
  - conditions:
    - condition: trigger
      id: up
    sequence:
    - choose:
      - conditions:
          - condition: or
            conditions:
            - condition: state
              entity_id:  !input raff
              state: opening
            - condition: state
              entity_id:  !input raff
              state: closing
        sequence:
          - service: cover.stop_cover
            data: {}
            target:
              entity_id:
                - !input raff
      default:
        - service: cover.open_cover
          data: {}
          target:
              entity_id:
                - !input raff
  - conditions:
    - condition: trigger
      id: down
    sequence:
    - choose:
      - conditions:       
        - condition: or
          conditions:
          - condition: state
            entity_id:  !input raff
            state: opening
          - condition: state
            entity_id:  !input raff
            state: closing
        sequence:
          - service: cover.stop_cover
            data: {}
            target:
              entity_id:
                - !input raff
      default:
        - choose:
          - conditions:
            - condition: state
              entity_id: !input window_sensor
              state: "off"
            sequence:
            - service: cover.close_cover
              data: {}
              target:
                  entity_id:
                    - !input raff
  default:
    - choose:
      - conditions:
        - condition: state
          entity_id: !input window_sensor
          state: "on"
        sequence:
          - service: cover.open_cover
            data: {}
            target:
              entity_id:
                - !input raff
      - conditions:
        - condition: state
          entity_id: !input raff
          state: "closing"
        sequence:

      default:
        - choose:
          - conditions:
            - condition: sun
              before: sunset
              after: sunrise
              before_offset: !input sunset_offset
              after_offset: !input sunrise_offset
            sequence:
            - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input outside_temperature
                    below: !input outside_control_temp_low
                sequence:
                  - service: cover.open_cover
                    data: {}
                    target:
                      entity_id:
                        - !input raff
              - conditions:
                  - condition: numeric_state
                    entity_id: !input outside_temperature
                    above: !input outside_control_temp
                sequence:
                - choose:
                  - conditions:
                    - condition: state
                      entity_id: !input window_sensor
                      state: "off"
                    sequence:
                    - service: cover.close_cover
                      data: {}
                      target:
                          entity_id:
                            - !input raff
                    - service: cover.set_cover_tilt_position
                      data:
                        tilt_position: !input outside_control_close
                      target:
                          entity_id:
                            - !input raff
          default:
            - choose:
              - conditions:
                - condition: sun
                  before: sunset
                  after: sunrise
                sequence:
                - choose:
                  - conditions:
                    - condition: state
                      entity_id: !input window_sensor
                      state: "off"
                    sequence:
                    - service: cover.close_cover
                      data: {}
                      target:
                          entity_id:
                            - !input raff
                    - service: cover.set_cover_tilt_position
                      data:
                        tilt_position: !input outside_control_close
                      target:
                          entity_id:
                            - !input raff
              default:
              - choose:
                - conditions:
                  - condition: state
                    entity_id: !input window_sensor
                    state: "off"
                  sequence:
                  - service: cover.close_cover
                    data: {}
                    target:
                        entity_id:
                          - !input raff
                  - service: cover.set_cover_tilt_position
                    data:
                      tilt_position: !input close_if_dark
                    target:
                        entity_id:
                          - !input raff