blueprint:
  name: RaffstoresteuerungV2
  description: Steuert Jalousien basierend auf Sonnenstand, Wind, Regen und manueller Eingabe.
  domain: automation
  source_url: https://raw.githubusercontent.com/MovingLlama/HomeAssistant/master/Blueprints/raffstore.yaml

input:
  switch:
    name: Schalter 1
    description: Entität, die Werte ändert, getestet mit Ikea Tradfri über Zigbee2MQTT
    selector:
      entity:
        domain: sensor
        multiple: false
  up:
    name: Öffnungswert Schalter 1
    description: Wert zum Öffnen der Jalousien
    default: auf
  down:
    name: Schließwert Schalter 1
    description: Wert zum Schließen der Jalousien
    default: zu
  switch_2:
    name: Schalter 2
    selector:
      entity:
        domain: sensor
        multiple: false
  up_2:
    name: Öffnungswert Schalter 2
    description: Wert zum Öffnen der Jalousien
    default: auf
  down_2:
    name: Schließwert Schalter 2
    description: Wert zum Schließen der Jalousien
    default: zu
  raff:
    name: Jalousien-Entität
    selector:
      entity:
        domain: cover
        multiple: false
  sunrise_offset:
    name: Offset Sonnenaufgang
    description: Offset für die Sonnenaufgangszeit
    default: 00:20:00
    selector:
      text: {}
  sunset_offset:
    name: Offset Sonnenuntergang
    description: Offset für die Sonnenuntergangszeit
    default: '-00:20:00'
    selector:
      text: {}
  outside_temperature:
    name: Außentemperatur
    description: Außentemperatur für die Heizungssteuerung
    default:
    selector:
      entity:
        domain: sensor
        device_class: temperature
        multiple: false
  outside_control_temp:
    name: Schwellenwert für Öffnungstemperatur
    description: Temperatur, bei der die Jalousien geöffnet werden
    default: 15
    selector:
      number:
        max: 40.0
        min: 10.0
        step: 1.0
        unit_of_measurement: °C
        mode: slider
  outside_control_temp_low:
    name: Schwellenwert für Öffnungstemperatur (niedrig)
    description: Temperatur, bei der die Jalousien geöffnet werden
    default: 15
    selector:
      number:
        max: 40.0
        min: 10.0
        step: 1.0
        unit_of_measurement: °C
        mode: slider
  outside_control_close:
    name: Schließtemperatur-Offset
    description: Wie weit werden die Jalousien geschlossen, wenn es heiß ist
    default: 75
    selector:
      number:
        max: 100.0
        min: 0.0
        step: 1.0
        unit_of_measurement: '%'
        mode: slider
  close_if_dark:
    name: Schließ-Offset nach Einbruch der Dunkelheit
    description: Wie weit werden die Jalousien geschlossen, wenn es Abend ist
    default: 30
    selector:
      number:
        max: 100.0
        min: 0.0
        step: 1.0
        unit_of_measurement: '%'
        mode: slider
  window_sensor:
    name: Fenstersensor
    default: input_boolean.helperfakesensor
    selector:
      entity:
        domain: binary_sensor
        multiple: false

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input switch
    to: !input up
    id: up
  - platform: state
    entity_id: !input switch
    to: !input down
    id: down
  - platform: state
    entity_id: !input switch_2
    to: !input up_2
    id: up
  - platform: state
    entity_id: !input window_sensor
    to: 'on'
    id: up
  - platform: state
    entity_id: !input window_sensor
  - platform: state
    entity_id: !input switch_2
    to: !input down_2
    id: down
  - platform: sun
    event: sunset
    offset: !input sunset_offset
  - platform: sun
    event: sunset
  - platform: sun
    event: sunrise
    offset: !input sunrise_offset
  - platform: sun
    event: sunrise
  - platform: numeric_state
    entity_id: !input outside_temperature
    above: !input outside_control_temp
  - platform: numeric_state
    entity_id: !input outside_temperature
    below: !input outside_control_temp_low
  - platform: state
    entity_id: !input raff
    to: 'closing'

action:
  - choose:
    - conditions:
      - condition: trigger
        id: up
      sequence:
        - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input raff
                    state: opening
                  - condition: state
                    entity_id: !input raff
                    state: closing
            sequence:
              - service: cover.stop_cover
                data: {}
                target:
                  entity_id: !input raff
          default:
            - service: cover.open_cover
              data: {}
              target:
                entity_id: !input raff
    - conditions:
      - condition: trigger
        id: down
      sequence:
        - choose:
          - conditions:       
            - condition: or
              conditions:
                - condition: state
                  entity_id: !input raff
                  state: opening
                - condition: state
                  entity_id: !input raff
                  state: closing
            sequence:
              - service: cover.stop_cover
                data: {}
                target:
                  entity_id: !input raff
          default:
            - choose:
              - conditions:
                - condition: state
                  entity_id: !input window_sensor
                  state: "off"
              sequence:
                - service: cover.close_cover
                  data: {}
                  target:
                    entity_id: !input raff
  default:
    - choose:
      - conditions:
        - condition: state
          entity_id: !input window_sensor
          state: "on"
        sequence:
          - service: cover.open_cover
            data: {}
            target:
              entity_id: !input raff
      - conditions:
        - condition: state
          entity_id: !input raff
          state: "closing"
        sequence:

      default:
        - choose:
          - conditions:
            - condition: sun
              before: sunset
              after: sunrise
              before_offset: !input sunset_offset
              after_offset: !input sunrise_offset
            sequence:
              - choose:
                - conditions:
                    - condition: numeric_state
                      entity_id: !input outside_temperature
                      below: !input outside_control_temp_low
                  sequence:
                    - service: cover.open_cover
                      data: {}
                      target:
                        entity_id: !input raff
                - conditions:
                    - condition: numeric_state
                      entity_id: !input outside_temperature
                      above: !input outside_control_temp
                  sequence:
                    - choose:
                      - conditions:
                        - condition: state
                          entity_id: !input window_sensor
                          state: "off"
                        sequence:
                          - service: cover.close_cover
                            data: {}
                            target:
                              entity_id: !input raff
                          - service: cover.set_cover_tilt_position
                            data:
                              tilt_position: !input outside_control_close
                            target:
                              entity_id: !input raff
          default:
            - choose:
              - conditions:
                - condition: sun
                  before: sunset
                  after: sunrise
              sequence:
                - choose:
                  - conditions:
                    - condition: state
                      entity_id: !input window_sensor
                      state: "off"
                    sequence:
                      - service: cover.close_cover
                        data: {}
                        target:
                          entity_id: !input raff
                      - service: cover.set_cover_tilt_position
                        data:
                          tilt_position: !input outside_control_close
                        target:
                          entity_id: !input raff
              default:
              - choose:
                - conditions:
                  - condition: state
                    entity_id: !input window_sensor
                    state: "off"
                  sequence:
                    - service: cover.close_cover
                      data: {}
                      target:
                        entity_id: !input raff
                    - service: cover.set_cover_tilt_position
                      data:
                        tilt_position: !input close_if_dark
                      target:
                        entity_id: !input raff
