blueprint:
  name: Rolladen Steuerung
  description: Steuert die Rolläden basierend auf diversen Werten
  domain: automation
  source_url: https://github.com/MovingLlama/HomeAssistant/blob/master/Blueprints/rolladen.yaml
  input:
    schalter_auf:
      name: Schalter
      selector:
        entity:
          domain: sensor
    rolladen:
      name: Rolladen
      selector:
        target:
          entity:
            domain: cover

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input schalter_auf
action:
  - service: cover.close_cover
    data: {}
    target: !input rolladen
