blueprint:
  name: Cover Controll
  description: Controlling Covers based on Sun state, Wind, Rain and manual imput.
  domain: automation
  source_url: https://github.com/MovingLlama/HomeAssistant/blob/master/Blueprints/rolladen.yaml
  input:
    switch:
      name: Switch
      description: Entity that is changing Values, testet with Ikea tradfri via zigbee2mqtt
      selector:
        entity:
          domain: sensor
    up:
      name: Up Value
      description: Value for opening covers
      default: up
    down:
      name: Down Value
      description: Value for closing covers
      default: down
    cover:
      name: Cover
      selector:
        target:
          entity:
            domain: cover

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input switch
action:
  - if:
    - condition: state
      entity_id: !input switch
      state : !input up
    then:
      - service: cover.open_cover
        data: {}
        target: !input cover
    else:
      - service: cover.close_cover
        date: {}
        target: !input cover